version: '3'

services:
  nginx:
    build: .
    container_name: nginx
    restart: "always"
    privileged: true
    links:
      - "webapp:verify-app"
    ports:
      - "80:80"

  jhd-bot:
    build: JHDBot/.
    container_name: jhd-bot
    restart: "unless-stopped"
    environment:
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
      - BOT_PREFIX_KEY=${BOT_PREFIX_KEY}

  webapp:
    build: verify-web/.
    container_name: verify-app
    restart: "always"
    environment:
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - CSRF_SECRET_KEY=${CSRF_SECRET_KEY}
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
      - DISCORD_SERVER_CHANNEL_ID=${DISCORD_SERVER_CHANNEL_ID}
