version: '3'

services:
  jhd-bot:
    build: JHDBot/.
    environment:
      - bot_token=${DISCORD_API_TOKEN}
  webapp:
    build: verify-web/.
    links:
      - "jhd-bot:jhd-bot"
    depends_on:
      - "jhd-bot"
    ports:
      - "8080:8080"
    environment:
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - CSRF_SECRET_KEY=${CSRF_SECRET_KEY}
