version: '3'

services:
  nginx:
    build: .
    container_name: nginx
    restart: "always"
    privileged: true
    links:
      - "webapp1:verify-app1"
      - "webapp2:verify-app2"
    ports:
      - "8080:80"

  jhd-bot:
    build: JHDBot/.
    container_name: jhd-bot
    restart: "always"
    volumes:
      - ./JHDBot/gifs:/usr/src/app/gifs:rw
    environment:
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
      - BOT_PREFIX_CHARACTER=${BOT_PREFIX_CHARACTER}
      - LOGGING_WEBHOOK_CHANNEL=${LOGGING_WEBHOOK_CHANNEL}
      - LOGGING_WEBHOOK_TOKEN=${LOGGING_WEBHOOK_TOKEN}

  webapp1:
    build: verify-web/.
    container_name: verify-app1
    restart: "always"
    environment:
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
      - DISCORD_SERVER_CHANNEL_ID=${DISCORD_SERVER_CHANNEL_ID}
      - LOGGING_WEBHOOK_CHANNEL=${LOGGING_WEBHOOK_CHANNEL}
      - LOGGING_WEBHOOK_TOKEN=${LOGGING_WEBHOOK_TOKEN}

  webapp2:
    build: verify-web/.
    container_name: verify-app2
    restart: "always"
    environment:
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
      - DISCORD_SERVER_CHANNEL_ID=${DISCORD_SERVER_CHANNEL_ID}
      - LOGGING_WEBHOOK_CHANNEL=${LOGGING_WEBHOOK_CHANNEL}
      - LOGGING_WEBHOOK_TOKEN=${LOGGING_WEBHOOK_TOKEN}
